[package]
name = "zik-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "~0.27.0", features = ["bundled"] }
metaflac = "~0.2"
directories = "~4.0"


